-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS "IIAEMS".courses_enrollment DROP CONSTRAINT IF EXISTS instructor_id;

ALTER TABLE IF EXISTS "IIAEMS".courses_enrollment DROP CONSTRAINT IF EXISTS course_id;

ALTER TABLE IF EXISTS "IIAEMS".courses_enrollment DROP CONSTRAINT IF EXISTS student_id;

ALTER TABLE IF EXISTS "IIAEMS".marks DROP CONSTRAINT IF EXISTS enrollment_id;

ALTER TABLE IF EXISTS "IIAEMS".payments DROP CONSTRAINT IF EXISTS enrollment_id;

ALTER TABLE IF EXISTS "IIAEMS".research_project DROP CONSTRAINT IF EXISTS student_id;

ALTER TABLE IF EXISTS "IIAEMS".research_project DROP CONSTRAINT IF EXISTS instructor_id;



DROP TABLE IF EXISTS "IIAEMS".courses_enrollment;

CREATE TABLE IF NOT EXISTS "IIAEMS".courses_enrollment
(
    enrollment_id integer NOT NULL,
    student_id integer,
    course_id integer,
    insgtructor_id integer,
    enrollment_date date,
    course_cost numeric(10, 2),
    grade character varying(10),
    course_start_date date,
    course_end_date date,
    credit numeric(1),
    PRIMARY KEY (enrollment_id)
);

DROP TABLE IF EXISTS "IIAEMS".courses;

CREATE TABLE IF NOT EXISTS "IIAEMS".courses
(
    course_id integer NOT NULL,
    course_name character varying(255),
    department_id integer,
    instructor_id integer,
    course_description text,
    PRIMARY KEY (course_id)
);

DROP TABLE IF EXISTS "IIAEMS".marks;

CREATE TABLE IF NOT EXISTS "IIAEMS".marks
(
    mark_id integer NOT NULL,
    enrollment_id integer,
    mark_type character varying(50),
    percentage numeric(3, 2),
    mark numeric(3, 2),
    PRIMARY KEY (mark_id)
);

DROP TABLE IF EXISTS "IIAEMS".instructors;

CREATE TABLE IF NOT EXISTS "IIAEMS".instructors
(
    instructor_id integer NOT NULL,
    first_name character varying(50),
    last_name character varying(50),
    email character varying(100),
    phone character varying(100),
    title character varying(50),
    PRIMARY KEY (instructor_id)
);

DROP TABLE IF EXISTS "IIAEMS".students;

CREATE TABLE IF NOT EXISTS "IIAEMS".students
(
    student_id integer NOT NULL,
    first_name character varying(100),
    last_name character varying(100),
    date_of_birth date,
    gender character varying(20),
    email character varying(100),
    phone character varying(20),
    address character varying(255),
    course_id integer,
    graduation_date date,
    PRIMARY KEY (student_id)
);

DROP TABLE IF EXISTS "IIAEMS".payments;

CREATE TABLE IF NOT EXISTS "IIAEMS".payments
(
    payment_id serial NOT NULL,
    enrollment_id integer,
    payment_amount numeric(10, 2),
    invoice_amount numeric(10, 2),
    payment_datetime timestamp with time zone NOT NULL DEFAULT current_timestamp,
    payment_method character varying(255),
    payment_reference character varying(255),
    payment_type character varying(255),
    PRIMARY KEY (payment_id)
);

DROP TABLE IF EXISTS "IIAEMS".research_project;

CREATE TABLE IF NOT EXISTS "IIAEMS".research_project
(
    id serial NOT NULL,
    student_id integer,
    instructor_id integer,
    project_id integer,
    project_title character varying(255),
    project_description text,
    project_start_date date,
    project_end_date date,
    project_material_url character varying(255),
    funding numeric(12, 2),
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS "IIAEMS".courses_enrollment
    ADD CONSTRAINT instructor_id FOREIGN KEY (insgtructor_id)
    REFERENCES "IIAEMS".instructors (instructor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "IIAEMS".courses_enrollment
    ADD CONSTRAINT course_id FOREIGN KEY (course_id)
    REFERENCES "IIAEMS".courses (course_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "IIAEMS".courses_enrollment
    ADD CONSTRAINT student_id FOREIGN KEY (student_id)
    REFERENCES "IIAEMS".students (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "IIAEMS".marks
    ADD CONSTRAINT enrollment_id FOREIGN KEY (enrollment_id)
    REFERENCES "IIAEMS".courses_enrollment (enrollment_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "IIAEMS".payments
    ADD CONSTRAINT enrollment_id FOREIGN KEY (enrollment_id)
    REFERENCES "IIAEMS".courses_enrollment (enrollment_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "IIAEMS".research_project
    ADD CONSTRAINT student_id FOREIGN KEY (student_id)
    REFERENCES "IIAEMS".students (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "IIAEMS".research_project
    ADD CONSTRAINT instructor_id FOREIGN KEY (instructor_id)
    REFERENCES "IIAEMS".instructors (instructor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;